# Generated by Django 2.2.24 on 2022-09-20 06:52

from django.db import migrations

from django.db import migrations

def new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year < 2015:
            flat.new_building = False
            flat.save()
        else:
            flat.new_building = True
            flat.save()

class Migration(migrations.Migration):
    dependencies = [
        ('property', '0002_auto_20220919_0903'),
    ]

    operations = [
        migrations.RunPython(new_building),
    ]
