# Generated by Django 3.2.6 on 2022-09-30 17:06
import phonenumbers
from django.db import migrations


def is_valid_number(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        parse_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(parse_number):
            flat.pure_phone = parse_number
            flat.save()
        else:
            flat.pure_phone = False
            flat.save()




class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20220930_1950'),
    ]

    operations = [
        migrations.RunPython(is_valid_number)
    ]
