# Generated by Django 3.2.6 on 2022-10-03 06:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20221001_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='owner',
            field=models.CharField(default=None, max_length=200, verbose_name='ФИО владельца'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='RU', verbose_name='Правильный номер владельца'),
        ),
        migrations.AddField(
            model_name='owner',
            name='owners_phonenumber',
            field=models.CharField(default=None, max_length=20, verbose_name='Номер владельца'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True),
        ),
    ]
