# Generated by Django 3.2.6 on 2022-10-03 06:52

from django.db import migrations


def fill_owner(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        Owner.objects.get_or_create(owner=flat.owner,
                                    owners_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phone=flat.pure_phone)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20221003_0952'),
    ]

    operations = [
        migrations.RunPython(fill_owner)
    ]
