# Generated by Django 3.2.6 on 2022-10-03 08:06

from django.db import migrations

def fill_flat_owners(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Flat = apps.get_model('property', 'Flat')
    for owner in Owner.objects.all().iterator():
        flats = Flat.objects.filter(owner=owner.owner)
        owner.flats.set(flats)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20221003_1105'),
    ]

    operations = [
        migrations.RunPython(fill_flat_owners)
    ]
